"""Initial migration.

Revision ID: 814c43dc2e99
Revises: 
Create Date: 2024-11-22 15:57:13.681266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814c43dc2e99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_db')
    # ### end Alembic commands ###
