"""Add field : Grade

Revision ID: ac6fc540546e
Revises: 814c43dc2e99
Create Date: 2025-01-02 15:28:32.673994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6fc540546e'
down_revision = '814c43dc2e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_db', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
