"""Change field : Grade, make nullable

Revision ID: e17e09173e21
Revises: ac6fc540546e
Create Date: 2025-01-02 15:30:41.668905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17e09173e21'
down_revision = 'ac6fc540546e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_db', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
