name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make setup
    
    - name: Run tests
      run: make test

    - name: Lint code
      run: make lint

    - name: Build docker image
      run: make build
    
    - name: Push docker image
      run: make push
